version: "3.1"
services:
  nginx:
    image:
      nginx:latest
    ports:
      - "8080:80"
    volumes:
      - "./public:/var/www/html"
      - "./nginx/default.conf:/etc/nginx/conf.d/default.conf"
      - "./logs/nginx/nginx-access.log:/var/log/nginx/access.log"
      - "./logs/nginx/nginx-error.log:/var/log/nginx/error.log"
    links:
      - php-fpm
    depends_on:
      - php-fpm
  php-fpm:
    build:
      context: php
      args:
        - WITH_XDEBUG=true
    ports:
      - "9000:9000"
    env_file:
      .env
    volumes:
      - "./public:/var/www/html"
      - "./php/php.ini:/usr/local/etc/php/conf.d/php.ini"
  mysql:
      build: ./mysql
      container_name: 'mysql'
      restart: 'always'
      ports:
        - "3306:3306"
      volumes:
        - "./data/db:/var/lib/mysql"
        - "./logs/mysql:/var/log/mysql"
      environment:
        MYSQL_ROOT_PASSWORD: secret

  adminer:
      image: adminer:4.7.6
      restart: always
      ports:
        - "8081:8080"
#    environment:
#      XDEBUG_CONFIG: "remote_host=host.docker.internal remote_enable=1"
#      PHP_IDE_CONFIG: "serverName=Docker"
